# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
sudo: false
cache: packages

r_packages:
   - data.table
   - stringr
   - seqinr
   - dplyr

repos:
    CRAN: https://cloud.r-project.org
    ropensci: http://packages.ropensci.org

notifications:
  email:
    on_success: change
    on_failure: change
