# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
cache: packages
warnings_are_errors: false
bioc_required: true

r_packages:
   - data.table
   - stringr
   - seqinr
   - dplyr

bioc_packages:
    - Biostrings

repos:
    CRAN: https://cloud.r-project.org
    ropensci: http://packages.ropensci.org

notifications:
  email:
    on_success: change
    on_failure: change
